spring:
    profiles:
        active: ${SPRING_PROFILE_ACTIVE}
    application:
        name: game-hub
    datasource:
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
            dialect: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
    mail:
        host: smtp.gmail.com
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    servlet:
        multipart:
            max-file-size: 500MB
            max-request-size: 500MB
